Task #1

In [3]:
ss=['Mercurio','Venus','Tierra','Marte','Jupiter','Saturno','Urano','Neptuno']
len(ss)

8

In [7]:
ss4=ss[0:4]
print(ss4)

['Mercurio', 'Venus', 'Tierra', 'Marte']


In [9]:
print(ss[1])

Venus


2° Task

In [17]:
temp_f=30.3
(5/9)*(temp_f-32)
temp_c=(5/9)*(temp_f-32)
print(temp_f)
print(temp_c)

30.3
-0.9444444444444441


3° Task

In [20]:
array=([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])
#1row 16 columns
print(array)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]


In [23]:
import numpy as np
fourxfour=np.reshape(array,(4,4))
print(fourxfour)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


4° Task

In [34]:
angulos=np.array([0,30,45,60,90])
radianes=angulos*(np.pi/180)
senoradines=np.sin(radianes)
cosradines=np.cos(radianes)
cosradines


array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

5° Task